type Frame = { seq: number; samples: number[] };
const STA_SIZE = 200; const LTA_SIZE = 6000; const PEAK_SIZE = 1000;
let running = true; let stationIds: number[] = []; let historySize = 120000; let metadata: Int32Array; let signalHistory: Float32Array; let timer: ReturnType<typeof setTimeout>;
const sequences = new Map<number, number>(); const queues = new Map<number, Frame[]>(); const samples = new Map<number, number[]>(); const peaks = new Map<number, number[]>(); const active = new Map<number, boolean>();
const stats = { received: 0, reordered: 0, duplicates: 0, lost: 0, late: 0 };
function getEnergy(channel: number) { const values = samples.get(channel) ?? []; let sta = 0; let lta = 0; for (let index = Math.max(0, values.length - STA_SIZE); index < values.length; index += 1) sta += values[index] ** 2; for (let index = Math.max(0, values.length - LTA_SIZE); index < values.length; index += 1) lta += values[index] ** 2; return { ratio: lta > 1 ? (sta / Math.min(STA_SIZE, values.length)) / (lta / Math.min(LTA_SIZE, values.length)) : 0, peak: Math.max(...(peaks.get(channel) ?? [0])) }; }
function handleFrame(station: number, channel: number, frame: Frame) { const channelId = (station - 1) * 3 + channel; const oldSequence = Atomics.load(metadata, channelId * 2); if (frame.seq <= oldSequence) { stats.duplicates += 1; return; } const values = samples.get(channelId) ?? []; const peakValues = peaks.get(channelId) ?? []; frame.samples.forEach((value) => { values.push(value); peakValues.push(Math.abs(value)); if (values.length > LTA_SIZE) values.shift(); if (peakValues.length > PEAK_SIZE) peakValues.shift(); const position = (Atomics.load(metadata, channelId * 2) + 1) % historySize; signalHistory[channelId * historySize + position] = value; Atomics.store(metadata, channelId * 2, Atomics.load(metadata, channelId * 2) + 1); }); samples.set(channelId, values); peaks.set(channelId, peakValues); const result = getEnergy(channelId); const nextActive = (active.get(channelId) ?? false) ? result.ratio > 1.5 : result.ratio >= 4; active.set(channelId, nextActive); self.postMessage({ type: "alarm", station, channel, ratio: result.ratio, peak: result.peak, active: nextActive }); }
function produce() { if (!running) return; stationIds.forEach((station) => [0, 1, 2].forEach((channel) => { const channelId = (station - 1) * 3 + channel; const next = (sequences.get(channelId) ?? 0) + 1; sequences.set(channelId, next); const burst = Math.floor(Date.now() / 3000) % 7 === 0 && station <= 5; const frame: Frame = { seq: next, samples: Array.from({ length: 50 }, (_, index) => Math.sin((next * 50 + index) / 9) * (burst ? 6500 : 500) + (Math.random() - 0.5) * 180) }; const queue = queues.get(channelId) ?? []; stats.received += 1; if (Math.random() < 0.008) { queue.push(frame); queue.push({ ...frame }); } else queue.push(frame); if (Math.random() < 0.04 && queue.length > 1) { queue.reverse(); stats.reordered += 1; } if (queue.length > 3) handleFrame(station, channel, queue.shift() as Frame); queues.set(channelId, queue); })); self.postMessage({ type: "stats", ...stats }); timer = setTimeout(produce, 250); }
self.onmessage = (event: MessageEvent<{ type: string; stations?: number[]; shared?: SharedArrayBuffer; historySize?: number }>) => { if (event.data.type === "start") { running = true; if (event.data.stations) stationIds = event.data.stations; if (event.data.shared) { historySize = event.data.historySize ?? historySize; metadata = new Int32Array(event.data.shared, 0, 54); signalHistory = new Float32Array(event.data.shared, 54 * Int32Array.BYTES_PER_ELEMENT); } clearTimeout(timer); produce(); } if (event.data.type === "stop") { running = false; clearTimeout(timer); } };
